version: '3.8'

services:
  angular-app:
    image: warehouse-management-app
    build:
      context: ./frontEnd
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    container_name: ware-house-app
    restart: unless-stopped